spring:
  application:
    name: bookstore-service
  datasource:  
     driver-class-name: org.mariadb.jdbc.Driver
     url: jdbc:mariadb://localhost:3306/compras
     username: compras
     password: 123456
  jpa: 
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        default_schema: compras